### ISSUE TITLE
Go build fails on Ubuntu

### ISSUE THREAD

**Issue by shime** [lpredova/njuhalo#42]
Thanks for the useful package.

I'd like to run it on Ubuntu, but I'm having problems building it (with go 1.8):

```
hrvoje@twobucks:~/njuhalo$ go build
../go/src/github.com/urfave/cli/docs.go:11:2: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
   /home/hrvoje/.go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
   /home/hrvoje/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
```

Any hints?

**Comment by lpredova** [comment]
Hi @shime . Thank you for using this tool!
I hope that you will find it useful 👍🏻

Regarding your issue, please checkout this branch https://github.com/lpredova/njuhalo/pull/43 and try again. It seems like urfave/cli wasn't vendored properly (it is not under packages https://github.com/lpredova/njuhalo/tree/master/vendor/github.com ) so I replaced tool that I use for vendoring and now it should be OK. 

Please try and let me know the outcome 🙏🏻

**Comment by shime** [comment]
Thank you! That fixed the problem with missing dependencies, but now I'm getting another one:

```
hrvoje@twobucks:~/go/src/njuhalo$ go build
# njuhalo
./main.go:77: undefined: command.ListItems
./main.go:86: undefined: command.Parse
```

I'm not experienced with go, so any hints are appreciated.

**Comment by lpredova** [comment]
Hmm that it odd 🤔. Let's try this:

From snippet you pasted i can see that project is under `/go/src`. I think that might be a problem.  In other programming languages this makes no sense because you can place your project anywhere but in GO it is really essential that a**ll code is under correct gopath and package name that relies on name of github repos**. So mv project on this path and try again.

`
$GOPATH/src/github.com/lpredova/njuhalo
`
Generally make sure that project is under correct $GOPATH - `echo $GOPATH`

**Comment by shime** [comment]
Oh my. Thanks so much! I've learned something today.

I've managed to build the project on Ubuntu and it works as expected now! 🎉🙌

THANK YOU!
